### PR TITLE
[#32] Asynchronous pull implemented

### LINKED ISSUE #32: Asynchronous pulling of images
A single dunner file can contain multiple images whose containers will have many commands to run. Pulling images from a remote server (like Docker hub) one by one is quite slow. Concurrent pulling of images can be implemented using `goroutines`.

### PR DESCRIPTION
**Pull request by ayushjn20**
Asynchronous pulling of images using `goroutines` and `waitGroups`. Resolves #32

### CODE REVIEW

**Comment by agentmilindu** [comment]
Superb job!

**Comment by ayushjn20** [comment]
@agentmilindu @rhperera @rehrumesh 
Please review.

**Comment by ayushjn20** [comment]
Hey @agentmilindu. For now, I think it's better to merge it on `develop` for now. Support for flags is next in my pipeline which is quite a big task. I will be working on that this week.

**Comment by ayushjn20** [comment]
Closed with reference to #34. Purpose fulfilled in #34.

**Comment by ayushjn20** [comment]
Closed with reference to #34. Purpose fulfilled in #34.

**Pull request closed without merging**
