### PR TITLE
Not throw validation errors on listing tasks

### LINKED ISSUE #156: Not throw validation error for env not set when listing tasks
When I do `dunner tasks` to see list of tasks, if it has a env variable reference but not set in the environment, it shows a validation error without listing.

Expected behaviour:

List of tasks should be shown.

### PR DESCRIPTION
**Pull request by apoorvam**
Fixes #156 

On `dunner tasks` no validation errors are shown. It will only be shown on `dunner do <task>`  or on `dunner validate`.

### CODE REVIEW

**Comment by apoorvam** [comment]
This file has 100% coverage, as per this: https://codecov.io/gh/leopardslab/dunner/pull/157/tree/pkg/dunner
Not sure why it shows as reduced. 🤔

**Comment by agentmilindu** [comment]
@apoorvam Can't we have the rest of the validations but just not the ENV resolution validation?

**Comment by agentmilindu** [comment]
@apoorvam plz resolve conflicts

**Comment by apoorvam** [comment]
> @apoorvam Can't we have the rest of the validations but just not the ENV resolution validation?

@agentmilindu We can, but env resolution is one of 3 custom validations we have. Making just one of it to skip doesnt seem nice here. Also, during listing its fine to not show other validations like host source mount directory does not exist. Let me know.

**Pull request merged**
