### PR TITLE
Build all binaries and packages in release branch, skip publish

### PR DESCRIPTION
**Pull request by apoorvam**
On branch with names as `release/v2.1.4` dunner binaries/packages are built to ensure its working fine. But its not published to any repository. This is done so that master branch does not fail if there is an error in building binaries during release. 

Steps to create a new release: 

* Make `release/<version>` branch from develop. (Release candidate)
* Make sure build passes 
* Merge it to `master` and back to `develop`
* Push a git tag to `release/<v>` branch as: 
    * Run `make release VERSION=v2.1.4` on cli
    * Run `git push origin <version>` to push tag to remote which makes dunner release!

@agentmilindu Please review the steps.

### CODE REVIEW

**Comment by agentmilindu** [comment]
@apoorvam Read this https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by apoorvam** [comment]
> @apoorvam Read this https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Cool, I updated the title message a bit based on this.

**Comment by apoorvam** [comment]
@agentmilindu After we branch from develop to release/<version> branch, we'll need a commit to trigger the build. Is there any way to do this?

**Comment by agentmilindu** [comment]
Once we branch out, I can create a tag and push

**Pull request merged**
