### PR TITLE
Add command `validate` to check for parse errors

### PR DESCRIPTION
**Pull request by apoorvam**
Adds a command `validate` to check for parse errors #31 #55

Running command `dunner validate` will check for any parse errors and warnings. If there are any errors, it fails the cmd. If not it finishes by listing any warnings if present.

Example:
```
$ dunner validate
ERRO[2019-03-22 17:15:56] dunner: [stats] Image repository name cannot be empty
```
Please let me know if there are any other validations for configs to be included.

### CODE REVIEW

**Comment by apoorvam** [comment]
@ayushjn20 You're right, We need to look for all kind of other validations. I'll try add the ones you suggested.

**Comment by agentmilindu** [comment]
Is there something similar to [Joi](https://github.com/hapijs/joi) for Golang?

**Comment by agentmilindu** [comment]
Can we use https://github.com/go-playground/validator?

See https://github.com/go-playground/validator/blob/v9/_examples/simple/main.go

**Comment by apoorvam** [comment]
I gave a shot at the `go-playground/validator` package. This is how it would look:

```
type Task struct {
	Name    string   `yaml:"name"`
	Image   string   `yaml:"image" validate:"required"`
	SubDir  string   `yaml:"dir"`
	Command []string `yaml:"command" validate:"required,gt=0,dive,required"`
	Envs    []string `yaml:"envs"`
	Mounts  []string `yaml:"mounts"`
	Args    []string `yaml:"args"`
}

type Configs struct {
	Tasks map[string][]Task `validate:"required,gt=0,dive,keys,required,endkeys,required,gt=0,dive,required"`
}

func (configs *Configs) Validate() ([]error) {
	var errs []error
	err := validator.New().Struct(configs)
	if (err != nil) {
		if _, ok := err.(*validator.InvalidValidationError); ok {
			errs = append(errs, err)
		} else {
			for _, e := range err.(validator.ValidationErrors) {
				errs = append(errs, fmt.Errorf("dunner: Validation for field '%s' failed on %s tag", e.Field(), e.Tag()))
			}
		}
	}
	return errs
}

```

* I think it can get complicated and requires to understand the DSL defined by library. 
* We cannot differentiate warnings and errors. 
* Error messages are not easy to be made user-friendly. The above code would give an error message like: `dunner: Validation for field 'Command' failed on gt tag`
To give more appropriate error message, we'll have to use translations like this: https://github.com/Aptomi/k8s-app-engine/blob/master/pkg/lang/validation.go#L98

Advantage is that messages can be uniform and easy to add more validations. I'll dig up more on if its worth it or probably write a custom validator. 
@agentmilindu Let me know if you have any thoughts on this.

**Comment by agentmilindu** [comment]
@apoorvam 

1. https://www.slideshare.net/surajssd009005/jsonschema-with-golang
2. https://stackoverflow.com/a/53230568/1190184

**Comment by apoorvam** [comment]
Update:

* `dunner validate` checks for any parse errors and validation errors. If there are any, it fails with non-zero exit code.
* Same validation is performed before `dunner do <task>` also.
* If any required fields are missing/empty, it gives error as below. It prefixes each error with task name so its easy to track error.
```
task 'stats': image is a required field
```
* In case of mount dir, it fails if its not in right format. Or if <src> directory is not present in the host machine. 
```
$ dunner validate
Validation failed for following errors:
task 'test': mount directory '/tmp/sample:/tmp' is invalid. Check format is '<valid_src_dir>:<valid_dest_dir>:<mode>' and has right permission level
```
* Added framework for add custom validations along with required context info. 

> Task is present or not when called as @taskName in a step of some other task.
> Sufficient number of arguments passed when one task is used as step for another task.

Above two validations should be added after [this](https://github.com/leopardslab/dunner/issues/58) change to use `follow` is implemented. Else it is just redundant. Will make it a part of new issue. 

@agentmilindu @ayushjn20 Please review.

**Pull request merged**
